Update 4-reload_gunicorn_no_downtime

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,6 +1,14 @@
 #!/usr/bin/env bash
-# gunicorn reload
+# Get the process ID of the Gunicorn master process
+main_pid=$(pgrep -f '^[^ ]*/?gunicorn ')
 
-pgrep gunicorn | xargs -r kill -HUP
-# restart
-sudo systemctl restart gunicorn
+# Check if the main_pid variable is empty
+if [ -z "$main_pid" ]; then
+        echo "Error: PID file not found"
+        exit 1
+fi
+
+# Send a termination signal to the Gunicorn master process
+kill -s TERM "$main_pid"
+
+# systemctl restart gunicorn.service
